#   conda env create -f environment.yml
name: segmentation
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - onnx
  - Pillow
  - tqdm
  - pip:
    - torch=1.13.1
    - torchvision=0.14.1
    - cityscapesscripts
    - opencv-python=4.1.2.30
    - onnxruntime-gpu
