name: segmentation
dependencies:
        - python=3.8
        - numpy
        - pillow
        - matplotlib
        - tqdm
        - opencv=4.2
        - onnxruntime-gpu
        - onnx
        - torch
        - torch-vision
