name: segmentation
dependencies:
        - python=3.8
        - numpy
        - pillow
        - matplotlib
        - tqdm
        - opencv-python=4.2.0.34
        - onnx
        #- onnxruntime-gpu
        #- torch
        #- torch-vision
